# tasks file for zsh

- name: Install ZSH
  package:
    name: zsh
    state: present
# - name: Get zsh path
#   command: which zsh
#   register: zsh_path_output
# - name: Ensure zsh is in /etc/shells
#   become: true
#   lineinfile:
#     path: /etc/shells
#     line: "{{ zsh_path_output.stdout }}"
#     state: present
# - name: Change shell to zsh
#   become: true
#   shell: "chsh -s {{ zsh_path_output.stdout }}"
- name: Remove .oh-my-zsh directory
  ansible.builtin.file:
    path: "{{ config_install_dir }}/.oh-my-zsh"
    state: absent
- name: Download Oh-My-Zsh
  shell: "curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > {{ config_install_dir }}/.oh-my-installer && chmod +x {{ config_install_dir }}/.oh-my-installer"
- name: Install Oh-My-Zsh
  register: result_oh_my_zsh_installer
  shell: "export ZSH={{ config_install_dir }}/.oh-my-zsh && {{ config_install_dir }}/.oh-my-installer --unattended"
- name: Oh-My-Zsh Output
  debug:
    msg: "{{ result_oh_my_zsh_installer.stdout }}"
- name: Create zsh symbolic link
  ansible.builtin.file:
    src: "{{ config_install_dir }}/.config/zsh/.zshrc"
    dest: "{{ config_install_dir }}/.zshrc"
    state: link
    force: true
    mode: '0755'
- name: Zsh plugin zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "{{ config_install_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
- name: Zsh plugin zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "{{ config_install_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
- name: Git reset to prevent any change on .zshrc
  shell: "cd {{ config_install_dir }}/.config && git reset --hard"
