# tasks file for tmux

- name: Install tmux
  apt:
    name: tmux
- name: Create the .tmux directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME2') }}/.tmux"
    state: directory
    mode: '0755'
- name: Clone tmux package manager tpm
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "{{ lookup('env', 'HOME2') }}/.tmux/plugins/tpm"
- name: Create tmux symbolic link
  ansible.builtin.file:
    src: "{{ lookup('env', 'HOME2') }}/.config/tmux/.tmux.conf"
    dest: "{{ lookup('env', 'HOME2') }}/.tmux.conf"
    state: link
    force: true
