- name: Pre tasks
  hosts: my-laptop
  gather_facts: true # mandatory to define the OS type
  pre_tasks:
    - name: Determine if we should become root
      set_fact:
        should_be_root: "{{ ansible_os_family == 'Debian' or ansible_os_family == 'RedHat' }}"
- name: Setup a new laptop
  hosts: my-laptop
  gather_facts: true # mandatory to define the OS type
  become: "{{should_be_root}}"
  vars_files:
    - ../vars/common.yml
  tasks:
    - name: Check if running as root
      debug:
        msg: "Running as root: {{ should_be_root }}"
    - name: Display current user used by Ansible
      debug:
        msg: "Current user used by Ansible: {{ ansible_env.USER }}"
    - ansible.builtin.include_role:
        name: nvim
    - ansible.builtin.include_role:
        name: zsh
    - ansible.builtin.include_role:
        name: tmux
    - ansible.builtin.include_role:
        name: kitty
      when: ansible_os_family == "Darwin" # install for Mac OS only
    - ansible.builtin.include_role:
        name: fzf
      when: ansible_os_family == "Darwin" # install for Mac OS only
    - ansible.builtin.include_role:
        name: tools
      when: ansible_os_family == "Darwin" # install for Mac OS only
